import { create } from 'zustand'
import { createJSONStorage, persist } from 'zustand/middleware'
import { CanvasEdge, CanvasNode, ExecutionPlan, ExecutionResult } from '../types/canvas'
import { createId } from '../utils/id'

interface CanvasState {
  nodes: CanvasNode[]; edges: CanvasEdge[]; pan: { x: number; y: number }; zoom: number; selectedNodeIds: string[]; activeIntentPrompt: string; isEvaluatingPlan: boolean; isExecutingPlan: boolean; activePlan: ExecutionPlan | null; executionResult: ExecutionResult | null; resetVersion: number
  setPan: (pan: { x: number; y: number }) => void; setZoom: (zoom: number) => void; addNode: (node: CanvasNode) => void; updateNode: (id: string, updates: { title: string; contentSummary: string }) => void; removeNode: (id: string) => void; updateNodePosition: (id: string, x: number, y: number) => 'updated' | 'collision' | 'invalid' | 'missing'; addEdge: (sourceId: string, targetId: string, relationType?: CanvasEdge['relationType'], label?: string) => void; removeEdge: (edgeId: string) => void; selectNode: (id: string, multi?: boolean) => void; clearSelection: () => void; setActiveIntentPrompt: (prompt: string) => void; setIsEvaluatingPlan: (evaluating: boolean) => void; setIsExecutingPlan: (executing: boolean) => void; setActivePlan: (plan: ExecutionPlan | null) => void; setExecutionResult: (result: ExecutionResult | null) => void; upsertOutputNode: (summary: string, payload: Record<string, unknown>) => boolean; clearCanvas: () => void
}
const WORKSPACE_STORAGE_KEY = 'intent-canvas.workspace'
const LEGACY_NODE_IDS = new Set(['node-account-health', 'node-customer-usage', 'node-renewal-calendar', 'node-customer-feedback', 'node-csm-notes', 'node-customer-txt', 'node-example-ui'])
const memoryStorage = { getItem: () => null, setItem: () => undefined, removeItem: () => undefined }
const NODE_GAP = 16
const nodeTypes = new Set(['document', 'dataset', 'instruction', 'output'])
function safePayload(value: unknown, depth = 0): boolean { if (depth > 4 || value == null || typeof value === 'boolean') return true; if (typeof value === 'number') return Number.isFinite(value); if (typeof value === 'string') return value.length <= 3000; if (Array.isArray(value)) return value.length <= 100 && value.every(item => safePayload(item, depth + 1)); if (typeof value !== 'object') return false; return Object.entries(value).length <= 100 && Object.entries(value).every(([key, item]) => key.length <= 160 && safePayload(item, depth + 1)) }
function validNode(value: unknown): value is CanvasNode { if (!value || typeof value !== 'object') return false; const node = value as Partial<CanvasNode>; const payload = node.dataPayload; const position = node.position; return typeof node.id === 'string' && /^[A-Za-z0-9_.:-]{1,120}$/.test(node.id) && typeof node.title === 'string' && node.title.length <= 300 && nodeTypes.has(node.type ?? '') && Boolean(position && [position.x, position.y, position.width, position.height].every(Number.isFinite) && position.width > 0 && position.width <= 2000 && position.height > 0 && position.height <= 2000) && Boolean(payload && typeof payload.mimeType === 'string' && payload.mimeType.length <= 160 && typeof payload.contentSummary === 'string' && payload.contentSummary.length <= 10_000 && (!payload.rawReference || (typeof payload.rawReference === 'string' && payload.rawReference.length <= 500)) && (!payload.previewUrl || (typeof payload.previewUrl === 'string' && payload.previewUrl.startsWith('data:image/') && payload.previewUrl.length <= 600_000)) && (!payload.parsedMetrics || safePayload(payload.parsedMetrics))) }
function overlaps(a: CanvasNode['position'], b: CanvasNode['position']) { return a.x < b.x + b.width + NODE_GAP && a.x + a.width + NODE_GAP > b.x && a.y < b.y + b.height + NODE_GAP && a.y + a.height + NODE_GAP > b.y }
function freePosition(nodes: CanvasNode[], node: CanvasNode): CanvasNode['position'] { for (let index = 0; index < 1000; index += 1) { const candidate = { ...node.position, x: node.position.x + (index % 10) * (node.position.width + NODE_GAP), y: node.position.y + Math.floor(index / 10) * (node.position.height + NODE_GAP) }; if (!nodes.some(other => overlaps(candidate, other.position))) return candidate }; const bottom = nodes.reduce((max, item) => Math.max(max, item.position.y + item.position.height), node.position.y); return { ...node.position, y: bottom + NODE_GAP } }
function mergePersistedWorkspace(current: CanvasState, persisted: unknown): CanvasState { if (!persisted || typeof persisted !== 'object') return current; const stored = persisted as Partial<CanvasState>; if (!Array.isArray(stored.nodes)) return current; const ids = new Set<string>(); const nodes = stored.nodes.filter((node): node is CanvasNode => validNode(node) && !LEGACY_NODE_IDS.has(node.id) && !ids.has(node.id) && Boolean(ids.add(node.id))).slice(0, 30); const nodeIds = new Set(nodes.map(node => node.id)); const edgeIds = new Set<string>(); const pairs = new Set<string>(); const edges = Array.isArray(stored.edges) ? stored.edges.filter((edge): edge is CanvasEdge => { if (!edge || typeof edge !== 'object') return false; const item = edge as Partial<CanvasEdge>; const pair = [item.sourceNodeId, item.targetNodeId].sort().join('|'); if (typeof item.id !== 'string' || edgeIds.has(item.id) || typeof item.sourceNodeId !== 'string' || typeof item.targetNodeId !== 'string' || !nodeIds.has(item.sourceNodeId) || !nodeIds.has(item.targetNodeId) || item.sourceNodeId === item.targetNodeId || !['explicit_connector', 'spatial_proximity', 'enclosure_group', 'semantic_match'].includes(item.relationType ?? '') || pairs.has(pair)) return false; edgeIds.add(item.id); pairs.add(pair); return true }).slice(0, 60) : []; return { ...current, nodes, edges, activeIntentPrompt: typeof stored.activeIntentPrompt === 'string' ? stored.activeIntentPrompt.slice(0, 3000) : '' } }

export const useCanvasStore = create<CanvasState>()(persist((set) => ({
  nodes: [], edges: [], pan: { x: 0, y: 0 }, zoom: 1, selectedNodeIds: [], activeIntentPrompt: '', isEvaluatingPlan: false, isExecutingPlan: false, activePlan: null, executionResult: null, resetVersion: 0,
  setPan: pan => set({ pan: { x: Number.isFinite(pan.x) ? pan.x : 0, y: Number.isFinite(pan.y) ? pan.y : 0 } }), setZoom: zoom => set({ zoom: Number.isFinite(zoom) ? Math.min(Math.max(zoom, 0.5), 2) : 1 }),
  addNode: node => set(state => !validNode(node) || state.nodes.length >= 30 || state.nodes.some(item => item.id === node.id) ? state : { nodes: [...state.nodes, { ...node, position: freePosition(state.nodes, node) }] }),
  updateNode: (id, updates) => set(state => ({ nodes: state.nodes.map(node => node.id === id ? { ...node, title: updates.title.slice(0, 300), dataPayload: { ...node.dataPayload, contentSummary: updates.contentSummary.slice(0, 10_000) } } : node) })),
  removeNode: id => set(state => { const removed = state.nodes.find(node => node.id === id); return { nodes: state.nodes.filter(node => node.id !== id), edges: state.edges.filter(edge => edge.sourceNodeId !== id && edge.targetNodeId !== id), selectedNodeIds: state.selectedNodeIds.filter(selected => selected !== id), executionResult: removed?.type === 'output' ? null : state.executionResult } }),
  updateNodePosition: (id, x, y) => { let result: 'updated' | 'collision' | 'invalid' | 'missing' = 'missing'; set(state => { const moving = state.nodes.find(node => node.id === id); if (!moving) return state; if (!Number.isFinite(x) || !Number.isFinite(y)) { result = 'invalid'; return state }; const position = { ...moving.position, x, y }; if (state.nodes.some(node => node.id !== id && overlaps(position, node.position))) { result = 'collision'; return state }; result = 'updated'; return { nodes: state.nodes.map(node => node.id === id ? { ...node, position } : node) } }); return result },
  addEdge: (sourceNodeId, targetNodeId, relationType = 'explicit_connector', label = 'Financial evidence relation') => set(state => { if (state.edges.length >= 60 || sourceNodeId === targetNodeId || !state.nodes.some(node => node.id === sourceNodeId) || !state.nodes.some(node => node.id === targetNodeId) || !['explicit_connector', 'spatial_proximity', 'enclosure_group', 'semantic_match'].includes(relationType) || typeof label !== 'string' || label.length > 300 || state.edges.some(edge => (edge.sourceNodeId === sourceNodeId && edge.targetNodeId === targetNodeId) || (edge.sourceNodeId === targetNodeId && edge.targetNodeId === sourceNodeId))) return state; return { edges: [...state.edges, { id: createId('edge'), sourceNodeId, targetNodeId, relationType, label: label.slice(0, 300) }] } }),
  removeEdge: edgeId => set(state => ({ edges: state.edges.filter(edge => edge.id !== edgeId) })), selectNode: (id, multi) => set(state => !state.nodes.some(node => node.id === id) ? state : { selectedNodeIds: multi ? (state.selectedNodeIds.includes(id) ? state.selectedNodeIds.filter(item => item !== id) : [...state.selectedNodeIds, id]) : [id] }), clearSelection: () => set({ selectedNodeIds: [] }), setActiveIntentPrompt: activeIntentPrompt => set({ activeIntentPrompt: activeIntentPrompt.slice(0, 3000) }), setIsEvaluatingPlan: isEvaluatingPlan => set({ isEvaluatingPlan }), setIsExecutingPlan: isExecutingPlan => set({ isExecutingPlan }), setActivePlan: activePlan => set({ activePlan }), setExecutionResult: executionResult => set({ executionResult }),
  upsertOutputNode: (summary, payload) => { let inserted = true; set(state => { const title = 'Revenue Rescue Results'; const existing = state.nodes.find(node => node.type === 'output'); if (existing) return { nodes: state.nodes.map(node => node.id === existing.id ? { ...node, title, dataPayload: { ...node.dataPayload, contentSummary: summary, parsedMetrics: payload } } : node) }; if (state.nodes.length >= 30) { inserted = false; return state }; const draft: CanvasNode = { id: 'result', title, type: 'output', position: { x: 420, y: 360, width: 300, height: 180 }, dataPayload: { mimeType: 'application/json', contentSummary: summary } }; return { nodes: [...state.nodes, { ...draft, id: createId('node_output'), position: freePosition(state.nodes, draft), dataPayload: { ...draft.dataPayload, parsedMetrics: payload } }] } }); return inserted },
  clearCanvas: () => set(state => ({ nodes: [], edges: [], selectedNodeIds: [], activePlan: null, executionResult: null, activeIntentPrompt: '', isEvaluatingPlan: false, isExecutingPlan: false, resetVersion: state.resetVersion + 1 })),
}), { name: WORKSPACE_STORAGE_KEY, storage: createJSONStorage(() => typeof localStorage === 'undefined' ? memoryStorage : localStorage), partialize: state => ({ nodes: state.nodes.map(node => ({ ...node, dataPayload: (({ previewUrl: _previewUrl, ...payload }) => payload)(node.dataPayload) })), edges: state.edges, activeIntentPrompt: state.activeIntentPrompt }), merge: (persisted, current) => mergePersistedWorkspace(current as CanvasState, persisted) }))
