import React from 'react'
import { CalendarDays, ShieldAlert, Sparkles, X } from 'lucide-react'
import { SpotlightCard } from '../ui/SpotlightCard'
import { ExecutionResult, RenewalRescuePayload } from '../../types/canvas'
import { useCanvasStore } from '../../store/useCanvasStore'
import { sanitizeSvg } from '../../utils/sanitizeSvg'

export const ResultNodeCard: React.FC<{ result: ExecutionResult }> = ({ result }) => {
  const setExecutionResult = useCanvasStore(state => state.setExecutionResult)
  const rescue = result.outputPayload?.renewalRescue as RenewalRescuePayload | undefined
  const safeChart = sanitizeSvg(rescue?.riskChartSvg)
  return <div className="w-[420px] max-w-[calc(100vw-2rem)]"><SpotlightCard spotlightColor="rgba(0,255,135,.18)" className="relative border-[#00ff87]/40 bg-[#090a0f]/95 shadow-2xl backdrop-blur-2xl">
    <button type="button" aria-label="Close revenue-risk result" onClick={() => setExecutionResult(null)} className="absolute right-3.5 top-3.5 rounded-full border border-white/10 bg-white/5 p-1 text-neutral-400 hover:bg-white/10 hover:text-white"><X className="h-3.5 w-3.5" /></button>
    <div className="mb-3 flex items-center justify-between pr-8"><div className="flex items-center gap-2"><div className="rounded-lg border border-[#00ff87]/30 bg-[#00ff87]/10 p-1.5 text-[#00ff87]"><Sparkles className="h-4 w-4" /></div><div><h3 className="text-xs font-bold text-white">Revenue Rescue Results</h3><p className="text-[10px] text-neutral-400">Evidence-backed, no financial action taken</p></div></div><span className="rounded-full border border-[#00ff87]/30 bg-[#00ff87]/10 px-2.5 py-0.5 text-[10px] font-bold text-[#00ff87]">{Math.round(Math.max(0, Math.min(1, result.confidenceScore ?? 0)) * 100)}% match</span></div>
    <p className="mb-3 rounded-xl border border-white/[.08] bg-white/[.03] p-2.5 text-[11px] font-medium leading-relaxed text-neutral-200">{rescue?.executiveSummary || result.goalSummary}</p>
    {safeChart && <div className="mb-3 overflow-x-auto rounded-xl border border-white/[.08] bg-[#040406] p-2"><p className="mb-1 text-[10px] font-semibold text-neutral-400">Risk portfolio</p><div aria-label="Revenue-risk portfolio chart" dangerouslySetInnerHTML={{ __html: safeChart }} /></div>}
    {rescue?.riskRecords.length ? <div className="space-y-2">{rescue.riskRecords.map((record, index) => <div key={`${record.account}-${record.renewalDate}-${index}`} className="rounded-lg border border-white/10 bg-black/20 p-2"><div className="flex items-start justify-between gap-2"><div><p className="text-[11px] font-bold text-white">{record.account}</p><p className="mt-.5 text-[10px] text-neutral-400">${record.ARR.toLocaleString('en-US')} ARR <span className="mx-1 text-neutral-600">•</span><CalendarDays className="inline h-3 w-3" /> {record.renewalDate}</p></div><span className={`rounded-full px-2 py-.5 text-[9px] font-bold uppercase ${record.riskLevel === 'critical' ? 'bg-rose-500/20 text-rose-200' : record.riskLevel === 'high' ? 'bg-amber-500/20 text-amber-200' : 'bg-sky-500/20 text-sky-200'}`}>{record.riskLevel} risk</span></div><dl className="mt-2 space-y-1 text-[10px] leading-snug text-neutral-300"><div><dt className="inline font-semibold text-neutral-500">Driver:</dt> <dd className="inline">{record.driver}</dd></div><div><dt className="inline font-semibold text-neutral-500">Risk score:</dt> <dd className="inline">{record.riskScore} <span className="text-neutral-500">({record.riskScoreSource})</span></dd></div><div><dt className="block font-semibold text-neutral-500">Evidence:</dt><dd><ul className="mt-.5 list-disc space-y-.5 pl-4">{record.evidence.map((item, evidenceIndex) => <li key={`${evidenceIndex}-${item}`}>{item}</li>)}</ul></dd></div><div><dt className="inline font-semibold text-neutral-500">Recovery action:</dt> <dd className="inline text-[#b8ffd9]">{record.recommendedAction}</dd></div></dl><p className="mt-2 border-t border-white/5 pt-1.5 text-[10px] text-neutral-400"><strong className="text-neutral-200">Owner:</strong> {record.owner} <span className="mx-1 text-neutral-600">•</span><strong className="text-neutral-200">Deadline:</strong> {record.deadline}</p></div>)}</div> : <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-2.5 text-[10px] text-amber-200"><ShieldAlert className="mr-1 inline h-3.5 w-3.5" />No account record could be established. Add Dodo events or account evidence and run a new assessment.</div>}
  </SpotlightCard></div>
}
