import axios from 'axios'
import { APP_CONFIG, apiUrl } from './config'
import { DodoConnectionStatus, DodoSignal, ExecutionPlan, ExecutionResult, HistoricalImportResult, RecoveryCase, RenewalRescuePayload, RevenueOperationsOverview } from './types/canvas'

const MAX_SHORT_STRING = 500
const MAX_LONG_STRING = 3000
const MAX_OUTPUT_BYTES = 100_000
const MAX_SVG_BYTES = 50_000
const isBoundedString = (value: unknown, max = MAX_SHORT_STRING): value is string => typeof value === 'string' && value.length <= max
const isRequiredString = (value: unknown, max = MAX_SHORT_STRING): value is string => isBoundedString(value, max) && value.trim().length > 0
const isStringArray = (value: unknown, maxLength = 30): value is string[] => Array.isArray(value) && value.length <= maxLength && value.every(item => isBoundedString(item, MAX_LONG_STRING))

function isRenewalRescuePayload(value: unknown): value is RenewalRescuePayload {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false
  const payload = value as Partial<RenewalRescuePayload>
  if (!isBoundedString(payload.executiveSummary, MAX_LONG_STRING) || typeof payload.riskChartSvg !== 'string' || new TextEncoder().encode(payload.riskChartSvg).length > MAX_SVG_BYTES || !Array.isArray(payload.riskRecords) || payload.riskRecords.length > 100) return false
  return payload.riskRecords.every((record) => {
    if (!record || typeof record !== 'object' || Array.isArray(record)) return false
    const item = record as unknown as Record<string, unknown>
    return isBoundedString(item.account, MAX_LONG_STRING) && typeof item.ARR === 'number' && Number.isFinite(item.ARR) && item.ARR >= 0 && isBoundedString(item.renewalDate, MAX_LONG_STRING) && typeof item.riskScore === 'number' && Number.isInteger(item.riskScore) && item.riskScore >= 0 && item.riskScore <= 100 && ['supplied', 'derived'].includes(item.riskScoreSource as string) && ['critical', 'high', 'medium', 'low'].includes(item.riskLevel as string) && isStringArray(item.evidence, 10) && ['driver', 'recommendedAction', 'owner', 'deadline'].every((field) => isBoundedString(item[field], MAX_LONG_STRING))
  })
}

function isPlanStep(value: unknown): value is ExecutionPlan['steps'][number] {
  if (!value || typeof value !== 'object') return false
  const step = value as Partial<ExecutionPlan['steps'][number]>
  return typeof step.stepId === 'number' && Number.isInteger(step.stepId) && step.stepId === 1 && isRequiredString(step.title) && isRequiredString(step.description, MAX_LONG_STRING) && step.requiredCapability === 'RenewalRescue' && Array.isArray(step.inputNodeIds) && step.inputNodeIds.length > 0 && step.inputNodeIds.length <= 30 && step.inputNodeIds.every(isRequiredString) && ['pending', 'running', 'completed', 'failed'].includes(step.status ?? '')
}
function isPlanContextItem(value: unknown): boolean { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const item = value as { nodeId?: unknown; purpose?: unknown; spatialBasis?: unknown }; return isRequiredString(item.nodeId) && isRequiredString(item.purpose, MAX_LONG_STRING) && ['explicit_connector', 'spatial_proximity', 'enclosure_group', 'semantic_match', 'standalone'].includes(item.spatialBasis as string) }
function isWorkflowStage(value: unknown, index: number): boolean { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const stage = value as { stageId?: unknown; title?: unknown; description?: unknown; output?: unknown }; return stage.stageId === index + 1 && isRequiredString(stage.title) && isRequiredString(stage.description, MAX_LONG_STRING) && isRequiredString(stage.output, MAX_LONG_STRING) }

export const intentApi = axios.create({ baseURL: APP_CONFIG.apiBaseUrl, timeout: APP_CONFIG.apiTimeoutMs, maxContentLength: 200_000, maxBodyLength: 10_000_000, headers: { 'Content-Type': 'application/json' } })
if (APP_CONFIG.apiAccessToken) { intentApi.defaults.headers.common.Authorization = `Bearer ${APP_CONFIG.apiAccessToken}`; intentApi.defaults.headers.common['X-Intent-Canvas-Key'] = APP_CONFIG.apiAccessToken }
export const intentPath = (path: string) => apiUrl(path)
export function getApiErrorMessage(error: unknown, fallback: string): string { if (axios.isAxiosError(error)) { if (error.code === 'ECONNABORTED') return 'The request timed out. Please try again.'; if (!error.response) return 'The revenue service is unavailable. Check that the backend is running.'; const message = error.response.data?.error?.message ?? error.response.data?.message; if (typeof message === 'string') return message.slice(0, MAX_SHORT_STRING) }; return fallback }
export const isRequestCancelled = (error: unknown): boolean => axios.isCancel(error) || (typeof DOMException !== 'undefined' && error instanceof DOMException && error.name === 'AbortError')

export function isExecutionPlan(value: unknown): value is ExecutionPlan { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const plan = value as Partial<ExecutionPlan>; return (plan.planningMode === 'local_fallback' || plan.planningMode === undefined) && (plan.planningNotice === undefined || isBoundedString(plan.planningNotice)) && isRequiredString(plan.planId) && isRequiredString(plan.goalSummary, MAX_LONG_STRING) && typeof plan.confidenceScore === 'number' && Number.isFinite(plan.confidenceScore) && plan.confidenceScore >= 0 && plan.confidenceScore <= 1 && Array.isArray(plan.context) && plan.context.length > 0 && plan.context.length <= 30 && plan.context.every(isPlanContextItem) && isStringArray(plan.assumptions, 30) && isStringArray(plan.constraints, 30) && isStringArray(plan.expectedOutputs, 30) && isStringArray(plan.verification, 30) && Array.isArray(plan.workflowStages) && plan.workflowStages.length === 3 && plan.workflowStages.every(isWorkflowStage) && Array.isArray(plan.steps) && plan.steps.length === 1 && isPlanStep(plan.steps[0]) }
export function isExecutionResult(value: unknown): value is ExecutionResult { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const result = value as Partial<ExecutionResult>; if (result.executionStatus !== 'completed' || !isRequiredString(result.planId) || !isRequiredString(result.goalSummary, MAX_LONG_STRING) || typeof result.confidenceScore !== 'number' || !Number.isFinite(result.confidenceScore) || result.confidenceScore < 0 || result.confidenceScore > 1 || !Array.isArray(result.executedSteps) || result.executedSteps.length !== 1 || !isPlanStep(result.executedSteps[0]) || !result.outputPayload || typeof result.outputPayload !== 'object' || Array.isArray(result.outputPayload) || Object.keys(result.outputPayload).length !== 1 || !isRenewalRescuePayload(result.outputPayload.renewalRescue)) return false; try { return new TextEncoder().encode(JSON.stringify(result.outputPayload)).length <= MAX_OUTPUT_BYTES } catch { return false } }

export function isRecoveryCase(value: unknown): value is RecoveryCase { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const item = value as Partial<RecoveryCase>; return isRequiredString(item.caseId) && isRequiredString(item.eventId) && isRequiredString(item.eventType) && isRequiredString(item.account) && isBoundedString(item.riskReason, MAX_LONG_STRING) && ['detected', 'approved', 'recovered', 'escalated', 'ignored'].includes(item.status ?? '') && isBoundedString(item.createdAt) && isBoundedString(item.updatedAt) && Array.isArray(item.timeline) && item.timeline.length <= 20 && item.timeline.every(entry => entry && typeof entry === 'object' && isBoundedString((entry as { at?: unknown }).at) && isBoundedString((entry as { label?: unknown }).label) && isBoundedString((entry as { detail?: unknown }).detail, MAX_LONG_STRING)) && ['customerId', 'subscriptionId', 'currency', 'nextBillingDate', 'paymentStatus', 'analysisMeteredAt'].every(key => (item as Record<string, unknown>)[key] === undefined || isBoundedString((item as Record<string, unknown>)[key])) && (item.amount === undefined || (typeof item.amount === 'number' && Number.isFinite(item.amount))) && (item.action === undefined || (typeof item.action === 'object' && item.action !== null && ['customer_follow_up', 'payment_method_update'].includes(item.action.type ?? '') && isBoundedString(item.action.actionId) && isBoundedString(item.action.approvedAt) && isBoundedString(item.action.operator))) }
export function isDodoSignal(value: unknown): value is DodoSignal { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const signal = value as Partial<DodoSignal>; return isRequiredString(signal.signalId) && isRequiredString(signal.eventId) && isRequiredString(signal.eventType) && isRequiredString(signal.eventFamily) && isRequiredString(signal.title) && isBoundedString(signal.summary, MAX_LONG_STRING) && isRequiredString(signal.account) && isBoundedString(signal.occurredAt) && ['recovery_case', 'recovery', 'operational', 'context'].includes(signal.classification ?? '') && ['customerId', 'subscriptionId'].every(key => (signal as Record<string, unknown>)[key] === undefined || isBoundedString((signal as Record<string, unknown>)[key])) }
export function isRevenueOperationsOverview(value: unknown): value is RevenueOperationsOverview { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const overview = value as Partial<RevenueOperationsOverview>; const countMap = (map: unknown, keys: readonly string[]) => Boolean(map) && typeof map === 'object' && !Array.isArray(map) && keys.every(key => typeof (map as Record<string, unknown>)[key] === 'number' && Number.isSafeInteger((map as Record<string, number>)[key]) && (map as Record<string, number>)[key] >= 0); return isBoundedString(overview.generatedAt) && typeof overview.retainedSignalCount === 'number' && Number.isSafeInteger(overview.retainedSignalCount) && overview.retainedSignalCount >= 0 && countMap(overview.signalCounts, ['recovery_case', 'recovery', 'operational', 'context']) && countMap(overview.caseCounts, ['detected', 'approved', 'recovered', 'escalated', 'ignored']) && Array.isArray(overview.eventFamilies) && overview.eventFamilies.length <= 8 && overview.eventFamilies.every(item => item && typeof item === 'object' && isRequiredString(item.family) && typeof item.count === 'number' && Number.isSafeInteger(item.count) && item.count >= 0 && typeof item.recoveryCases === 'number' && Number.isSafeInteger(item.recoveryCases) && item.recoveryCases >= 0 && item.recoveryCases <= item.count) && Array.isArray(overview.attentionCases) && overview.attentionCases.length <= 5 && overview.attentionCases.every(item => item && typeof item === 'object' && isRequiredString(item.caseId) && isRequiredString(item.account) && isRequiredString(item.eventType) && isBoundedString(item.riskReason, MAX_LONG_STRING) && ['detected', 'escalated'].includes(item.status ?? '') && isBoundedString(item.updatedAt)) }
export function isDodoConnectionStatus(value: unknown): value is DodoConnectionStatus { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const status = value as Partial<DodoConnectionStatus>; return ['test_mode', 'live_mode'].includes(status.environment ?? '') && isBoundedString(status.webhookUrl, 1000) && typeof status.webhookSigningKeyConfigured === 'boolean' && typeof status.apiKeyConfigured === 'boolean' && typeof status.historyImportAvailable === 'boolean' }
export function isHistoricalImportResult(value: unknown): value is HistoricalImportResult { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const result = value as Partial<HistoricalImportResult>; return ['paymentsScanned', 'eventsImported', 'casesCreated'].every(key => typeof (result as Record<string, unknown>)[key] === 'number' && Number.isSafeInteger((result as Record<string, number>)[key]) && (result as Record<string, number>)[key] >= 0) && typeof result.hasMore === 'boolean' && (result.nextPage === undefined || (typeof result.nextPage === 'number' && Number.isSafeInteger(result.nextPage) && result.nextPage >= 0 && result.nextPage <= 100_000)) && (!result.hasMore || result.nextPage !== undefined) }
